version: '3'

volumes:
   geoserver-data:

services:
   geoserver:
      image: 439919391008.dkr.ecr.ap-northeast-2.amazonaws.com/geoserver:latest
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "8080:8080"
      # restart: on-failure
      env_file:
        - docker-env/geoserver.env
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
